import { StyleSheet } from 'react-native';

const colors = {
  primary: '#1F4FFF',
  secondary: '#0D3B95',
  tertiary: '#0F6CEA',
  accent: '#FFC107',
  background: '#F8F8F8',
  surface: '#FFFFFF',
  text: '#0D3B95',
  mutedText: '#5C6B89',
  lightBorder: '#DCE4FF',
  shadow: '#B8C9F6',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  topPanel: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingBottom: 22,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  brand: {
    color: colors.surface,
    fontFamily: 'Poppins_700Bold',
    fontSize: 28,
    letterSpacing: 0.3,
    marginTop: 4,
  },
  brandAccent: {
    color: colors.accent,
  },
  staysBadge: {
    alignItems: 'center',
    borderColor: colors.surface,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  badgeIcon: {
    backgroundColor: colors.surface,
    borderRadius: 6,
    height: 12,
    marginRight: 8,
    width: 12,
  },
  staysText: {
    color: colors.surface,
    fontFamily: 'Poppins_500Medium',
    fontSize: 14,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 28,
  },
  searchCard: {
    backgroundColor: colors.surface,
    borderColor: colors.accent,
    borderRadius: 999,
    borderWidth: 3,
    marginHorizontal: 16,
    marginTop: 38,
    overflow: 'hidden',
  },
  searchRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
  },
  searchField: {
    flex: 1,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  field: {
    borderBottomColor: colors.accent,
    borderBottomWidth: 2,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  fieldLabel: {
    color: colors.mutedText,
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    marginBottom: 4,
  },
  textInput: {
    color: colors.text,
    fontFamily: 'Poppins_400Regular',
    fontSize: 15,
    paddingVertical: 0,
  },
  inputText: {
    color: colors.text,
    fontFamily: 'Poppins_400Regular',
    fontSize: 15,
  },
  searchButton: {
    alignItems: 'center',
    backgroundColor: colors.tertiary,
    justifyContent: 'center',
    minHeight: 48,
  },
  searchButtonText: {
    color: colors.surface,
    fontFamily: 'Poppins_700Bold',
    fontSize: 18,
  },
  searchButtonInline: {
    alignItems: 'center',
    backgroundColor: colors.tertiary,
    borderBottomRightRadius: 999,
    borderTopRightRadius: 999,
    justifyContent: 'center',
    minWidth: 78,
  },
  searchButtonInlineText: {
    color: colors.surface,
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    marginTop: -2,
  },
  searchIcon: {
    color: colors.surface,
    fontFamily: 'Poppins_700Bold',
    fontSize: 30,
  },
  sectionHeader: {
    marginBottom: 14,
    marginHorizontal: 16,
    marginTop: 28,
  },
  sectionTitle: {
    color: colors.secondary,
    fontFamily: 'Poppins_700Bold',
    fontSize: 28,
    letterSpacing: -0.4,
  },
  sectionSubtitle: {
    color: colors.mutedText,
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    marginTop: 6,
  },
  dealsRow: {
    paddingHorizontal: 16,
  },
  dealCard: {
    backgroundColor: colors.surface,
    borderColor: colors.secondary,
    borderRadius: 16,
    borderWidth: 1,
    marginRight: 12,
    minHeight: 132,
    padding: 16,
    width: 250,
  },
  dealCardTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  dealTitle: {
    color: '#101010',
    flex: 1,
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
    paddingRight: 10,
  },
  dealDescription: {
    color: '#202020',
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 10,
  },
  cardsRow: {
    paddingHorizontal: 16,
  },
  weekendCard: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    elevation: 3,
    marginRight: 14,
    overflow: 'hidden',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    width: 210,
  },
  cardImage: {
    height: 170,
    width: '100%',
  },
  weekendCardBody: {
    flex: 1,
    padding: 14,
  },
  weekendCardTitle: {
    color: colors.secondary,
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    lineHeight: 22,
  },
  ratingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 6,
  },
  ratingBadge: {
    backgroundColor: colors.secondary,
    borderRadius: 4,
    marginRight: 6,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  ratingBadgeText: {
    color: colors.surface,
    fontFamily: 'Poppins_700Bold',
    fontSize: 11,
  },
  reviewText: {
    color: colors.mutedText,
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    marginRight: 4,
  },
  locationText: {
    color: colors.text,
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    marginTop: 10,
  },
  greenBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#15803D',
    borderRadius: 5,
    marginTop: 12,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  greenBadgeText: {
    color: colors.surface,
    fontFamily: 'Poppins_700Bold',
    fontSize: 12,
  },
  priceRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 'auto',
    paddingTop: 18,
  },
  nightsText: {
    color: colors.mutedText,
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    marginRight: 4,
  },
  oldPrice: {
    color: '#dc2626',
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    marginRight: 6,
    textDecorationLine: 'line-through',
  },
  newPrice: {
    color: colors.secondary,
    fontFamily: 'Poppins_700Bold',
    fontSize: 28,
  },
  attractionCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    elevation: 3,
    marginRight: 14,
    overflow: 'hidden',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    width: 224,
  },
  attractionImage: {
    height: 178,
    width: '100%',
  },
  attractionBody: {
    minHeight: 118,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  attractionTitle: {
    color: '#101010',
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
    lineHeight: 22,
    minHeight: 44,
  },
  attractionMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 10,
  },
  starIcon: {
    marginRight: 6,
  },
  attractionRating: {
    color: '#101010',
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    marginRight: 5,
  },
  attractionDot: {
    color: '#101010',
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    marginRight: 5,
  },
  attractionReviews: {
    color: '#6A6A6A',
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
  },
  attractionPriceRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    width: '100%',
  },
  attractionPriceLabel: {
    color: '#101010',
    fontFamily: 'Poppins_500Medium',
    fontSize: 14,
    marginLeft: 6,
  },
  attractionPrice: {
    color: '#101010',
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    marginRight: 4,
  },
  ideaCard: {
    borderRadius: 12,
    marginRight: 12,
    overflow: 'hidden',
    width: 182,
  },
  ideaImage: {
    height: 190,
    width: '100%',
  },
  ideaOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(13, 59, 149, 0.24)',
  },
  ideaTitle: {
    bottom: 14,
    color: colors.surface,
    fontFamily: 'Poppins_700Bold',
    fontSize: 20,
    left: 12,
    position: 'absolute',
  },
  bottomNav: {
    backgroundColor: colors.surface,
    borderTopColor: colors.lightBorder,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingBottom: 10,
    paddingHorizontal: 8,
    paddingTop: 10,
  },
  navItem: {
    alignItems: 'center',
    gap: 4,
  },
  navLabel: {
    color: '#101010',
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
  },
  navLabelActive: {
    color: '#101010',
    fontFamily: 'Poppins_500Medium',
  },
  modalBackdrop: {
    backgroundColor: 'rgba(17, 24, 39, 0.45)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 28,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  modalTitle: {
    color: colors.secondary,
    fontFamily: 'Poppins_700Bold',
    fontSize: 22,
  },
  modalClose: {
    color: colors.primary,
    fontFamily: 'Poppins_700Bold',
    fontSize: 15,
  },
  selectionSummary: {
    color: colors.mutedText,
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    marginBottom: 18,
  },
  monthSwitcher: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  monthButton: {
    alignItems: 'center',
    backgroundColor: '#EEF4FF',
    borderRadius: 999,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  monthButtonText: {
    color: colors.secondary,
    fontFamily: 'Poppins_700Bold',
    fontSize: 18,
  },
  monthLabel: {
    color: colors.secondary,
    fontFamily: 'Poppins_700Bold',
    fontSize: 18,
  },
  weekdaysRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  weekdayText: {
    color: colors.mutedText,
    fontFamily: 'Poppins_700Bold',
    fontSize: 12,
    textAlign: 'center',
    width: '14.28%',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 22,
  },
  emptyDay: {
    width: '14.28%',
  },
  dayCell: {
    alignItems: 'center',
    borderRadius: 14,
    height: 42,
    justifyContent: 'center',
    marginBottom: 8,
    width: '14.28%',
  },
  dayCellInRange: {
    backgroundColor: '#DCE4FF',
  },
  dayCellActive: {
    backgroundColor: colors.primary,
  },
  dayText: {
    color: colors.text,
    fontFamily: 'Poppins_500Medium',
    fontSize: 14,
  },
  dayTextActive: {
    color: colors.surface,
  },
  primaryModalButton: {
    alignItems: 'center',
    backgroundColor: colors.tertiary,
    borderRadius: 14,
    paddingVertical: 15,
  },
  primaryModalButtonText: {
    color: colors.surface,
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
  },
  counterRow: {
    alignItems: 'center',
    borderBottomColor: colors.lightBorder,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 16,
  },
  counterTextWrap: {
    flex: 1,
    paddingRight: 12,
  },
  counterLabel: {
    color: colors.secondary,
    fontFamily: 'Poppins_700Bold',
    fontSize: 17,
  },
  counterDescription: {
    color: colors.mutedText,
    fontFamily: 'Poppins_400Regular',
    fontSize: 13,
    marginTop: 4,
  },
  counterControls: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  counterButton: {
    alignItems: 'center',
    borderColor: colors.primary,
    borderRadius: 999,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  counterButtonDisabled: {
    borderColor: '#C8D2E6',
  },
  counterButtonText: {
    color: colors.primary,
    fontFamily: 'Poppins_700Bold',
    fontSize: 18,
  },
  counterValue: {
    color: colors.secondary,
    fontFamily: 'Poppins_700Bold',
    fontSize: 17,
    minWidth: 36,
    textAlign: 'center',
  },
  placeholderWrap: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  placeholderTitle: {
    color: colors.secondary,
    fontFamily: 'Poppins_700Bold',
    fontSize: 32,
    marginBottom: 10,
  },
  placeholderText: {
    color: colors.mutedText,
    fontFamily: 'Poppins_400Regular',
    fontSize: 15,
    textAlign: 'center',
  },
});
